version: 2.0
jobs:
  buildService:
    working_directory: /root/.go_workspace/src/github.com/lastmilelink/email-resource
    docker:
      - image: lmlt/builder:latest
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "glide.yaml" }}
      - run:
          name: glide install
          command: glide install
      - run:
          name: go test
          command: go test
      - setup_remote_docker
      - run:
          name: make
          command: make
      - run:
          name: Login to dockerhub
          command: echo "dperezmavrogenis@lastmilelink.com" | docker login --username "${DOCKER_CLOUD_USERNAME}" --password "${DOCKER_CLOUD_PASSWORD}"
      - run:
          name: docker build --tag lmlt/email-resource:latest .
          command: docker build --tag lmlt/email-resource:latest .
      - run:
          name: docker build --tag lmlt/email-resource:${CIRCLE_BUILD_NUM} .
          command: docker build --tag lmlt/email-resource:${CIRCLE_BUILD_NUM} .
      - run:
          name: Push Docker image versioned
          command: docker push lmlt/email-resource:${CIRCLE_BUILD_NUM}
      - run:
          name: Push Docker image latest
          command: docker push lmlt/email-resource:latest
      - save_cache:
          key: vendor-{{ checksum "glide.yaml" }}
          paths:
            - ./vendor

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - buildService:
          filters:
            branches:
              only:
                - master
