version: 2.0
jobs:
  buildService:
    working_directory: /root/.go_workspace/src/github.com/lastmilelink/email-resource
    docker:
      - image: lmlt/builder:latest
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "glide.yaml" }}
      - run:
          name: glide install
          command: glide install
      - run:
          name: go test
          command: cd out && go test
      - setup_remote_docker
      - run:
          name: make
          command: make
      - run:
          name: login to AWS ECR
          command: eval $(aws ecr get-login --no-include-email --region eu-west-1)
      - run:
          name: docker build
          command: docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/email-resource:latest . && docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/email-resource:${CIRCLE_BUILD_NUM} .
      - run:
          name: Push Docker image versioned
          command: docker push ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/email-resource:${CIRCLE_BUILD_NUM}
      - run:
          name: Push Docker image latest
          command: docker push ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/email-resource:latest
      - save_cache:
          key: vendor-{{ checksum "glide.yaml" }}
          paths:
            - ./vendor

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - buildService:
          filters:
            branches:
              only:
                - master
